### ISSUE TITLE
[M10] Continuous Deployment Setup with Vercel

### ISSUE THREAD

**Issue by ilyapaddubny** [ilyapaddubny/LinkNest#16]
## 📋 Overview
Set up automated deployment pipeline using GitHub Actions and Vercel for continuous delivery.

## ✅ Tasks
- [ ] Provision Neon PostgreSQL database
- [ ] Configure Vercel project
- [ ] Set up GitHub Actions workflow
- [ ] Configure environment variables
- [ ] Set up preview deployments for PRs
- [ ] Configure production deployment from main
- [ ] Set up deployment notifications
- [ ] Create deployment documentation

## 🗄️ Database Setup (Neon)
1. Create Neon project
2. Set up production and preview databases
3. Configure connection pooling
4. Set up automated backups
5. Configure database branching for previews

## 🚀 Vercel Configuration
```json
// vercel.json
{
  "buildCommand": "pnpm build",
  "devCommand": "pnpm dev",
  "installCommand": "pnpm install",
  "framework": "nextjs",
  "outputDirectory": ".next",
  "env": {
    "DATABASE_URL": "@database-url",
    "NEXTAUTH_URL": "@nextauth-url",
    "NEXTAUTH_SECRET": "@nextauth-secret"
  }
}
```

## 🔄 GitHub Actions Workflow
```yaml
# .github/workflows/deploy.yml
name: Deploy to Production
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test:ci
      - name: Run Prisma migrations
        run: pnpm prisma migrate deploy
      - name: Deploy to Vercel
        run: vercel --prod
```

## 🔐 Environment Variables
- Production: Set in Vercel dashboard
- Preview: Auto-populated from production
- Local: .env.local (git-ignored)

Required variables:
- DATABASE_URL
- NEXTAUTH_SECRET
- NEXTAUTH_URL
- GITHUB_CLIENT_ID
- GITHUB_CLIENT_SECRET
- GOOGLE_CLIENT_ID
- GOOGLE_CLIENT_SECRET

## ✨ Acceptance Criteria
- [ ] Every PR gets preview deployment
- [ ] Main branch auto-deploys to production
- [ ] Database migrations run automatically
- [ ] Environment variables properly configured
- [ ] Deployment completes in < 5 minutes
- [ ] Rollback process documented
